### ISSUE TITLE
Array of references not showing up

### ISSUE THREAD

**Issue by bastibuck** [ahmdigital/content-model-graph#6]
Thanks for that plugin! Really easy to use 👍 

There's a little catch though that I stumpled upon. 

![image](https://user-images.githubusercontent.com/6306291/68997341-a50dea00-08a5-11ea-9274-b71c22c40985.png)

The schema is in german, sorry about that, if it makes it easier to understand I will translate it for you, but I think you will get the idea:

The "Gerichte" document is not totally isolated as it appears in the graph but is actually referenced in the "Runden" document. It is references inside an array of references. So my guess is that references in that form are not correctly displayed yet.

Here's the part of the "Runden" schema where the *dishes* are referenced
```js
{
      title: "Gerichte",
      name: "dishes",
      type: "array",
      of: [
        {
          type: "reference",
          to: [{ type: "dish" }],
        },
      ],
    },
```

Let me know if you need any other info or help.

**Comment by camjc** [comment]
Hey @bastibuck, I don’t yet support non-graphql-valid schemas. Something that’s worthwhile adding probably though. I guess we need to keep recursing down the object until we hit a leaf node.

**Comment by bastibuck** [comment]
Sounds good. Didn't dive into graphql that much yet but maybe you can enlighten me: why is that not valid? I find it to be a pretty standard way of referencing stuff or can/should I do that differently?

There probably is a good reason why this pattern isn't valid in graphql which is pretty well thought out it seems ;-)

**Comment by camjc** [comment]
Sorry for lack of clarity and maybe I’m even incorrect. It’s my impression that to publish a graphql endpoint in sanity you have to hoist objects to be top-level documents. Can still reference them though.

I may be completely misinterpreting this request in any case. Would it be possible to have the whole schema snapshot (or even the relevant bits) up til a type:document?

**Comment by bastibuck** [comment]
Sure thing :-) Here you go

schema.js (my main file that includes sub schemas)
```js
// First, we must import the schema creator
import createSchema from "part:@sanity/base/schema-creator";

// Then import schema types from any plugins that might expose them
import schemaTypes from "all:part:@sanity/base/schema-type";

// import schemas
import friend from "./friend";
import round from "./round";
import dish from "./dish";
import season from "./season";

export default createSchema({
  name: "kochrundeSchema",
  types: schemaTypes.concat([friend, round, dish, season]),
});
```

round.js
This is where the issue is inside I think. It has an array of rerefences to dishes which are not represented in the graph. They show up though but are not properly connected like the cooks/friends and seasons are.
```js
export default {
  title: "Runden",
  name: "round",
  type: "document",

  fields: [
    {
      title: "Titel",
      name: "title",
      type: "string",
      validation: Rule => Rule.required(),
    },
    {
      title: "Datum",
      name: "date",
      type: "datetime",

      options: {
        dateFormat: "DD.MM.YYYY",
      },
      validation: Rule => Rule.required(),
    },
    {
      title: "Koch",
      name: "cook",
      type: "reference",

      to: [{ type: "friend" }],
      validation: Rule => Rule.required(),
    },
    {
      title: "Saison",
      name: "season",
      type: "reference",
      to: [{ type: "season" }],
      validation: Rule => Rule.required(),
    },
    {
      title: "Gerichte",
      name: "dishes",
      type: "array",
      of: [
        {
          type: "reference",
          to: [{ type: "dish" }],
        },
      ],
    },
  ],
  orderings: [
    {
      title: "Datum, absteigend",
      name: "dateDesc",
      by: [{ field: "date", direction: "desc" }],
    },
    {
      title: "Datum, aufsteigend",
      name: "dateDesc",
      by: [{ field: "date", direction: "asc" }],
    },
    {
      title: "Koch, A-Z",
      name: "cookAsc",
      by: [{ field: "cook.name", direction: "asc" }],
    },
    {
      title: "Koch, Z-A",
      name: "cookDesc",
      by: [{ field: "cook.name", direction: "desc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      date: "date",
      cook: "cook.name",
    },
    prepare(selection) {
      const { title, date, cook } = selection;
      const dateLocalized = new Date(date).toLocaleDateString("de", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
      });

      return {
        title,
        subtitle: `${dateLocalized} | ${cook}`,
      };
    },
  },
};
```


friend.js
```js
export default {
  title: "Freunde",
  name: "friend",
  type: "document",
  fields: [
    {
      title: "Name",
      name: "name",
      type: "string",
      validation: Rule => Rule.required(),
    },
    {
      title: "Profilfoto",
      name: "profile_picture",
      type: "image",
    },
  ],
};
```

dish.js
```js
export default {
  title: "Gerichte",
  name: "dish",
  type: "document",
  fields: [
    {
      title: "Name",
      name: "name",
      type: "string",
      validation: Rule => Rule.required(),
    },
    {
      title: "Gang",
      name: "course",
      type: "string",
      options: {
        list: [
          { title: "Vorspeise", value: "starter" },
          { title: "Hauptgang", value: "main" },
          { title: "Dessert", value: "dessert" },
        ],
        layout: "radio",
      },
      validation: Rule => Rule.required(),
    },
    {
      title: "Foto",
      name: "image",
      type: "image",
    },
    {
      title: "Rezept",
      name: "recipe",
      type: "url",
    },
  ],
};
```

season.js
```js
export default {
  title: "Saison",
  name: "season",
  type: "document",
  fields: [
    {
      title: "Titel",
      name: "title",
      type: "string",
      validation: Rule => Rule.required(),
    },
  ],
};
```

I hope this helps to get my issue across a little bit better. Otherwise I can explain more if needed.

**Comment by tarjelavik** [comment]
I do a lot of these arrays of references. If your tool could show these relations too, it would make it a great way for users to get to grips with bigger sanity models 😄.
I have hoisted everything, and can build the graphql endpoint. In the end i found `groq` way easier.

**Comment by thompcd** [comment]
@camjc you're correct that Sanity requires hoisting to the top, but that's an artificial constraint on Sanity's implementation of GraphQL in order to maintain compatibility in other places. This is a valid schema, just not fully supported by Sanity

**Comment by tarjelavik** [comment]
Will this be solved by sanity v0.145.0 (https://github.com/sanity-io/sanity/releases/tag/v0.145.0)?

> A long-standing bug has prevented named reference and array types defined in the types array of your schema to be used in GraphQL schemas. This is now finally fixed - hooray! 🎉

**Comment by bastibuck** [comment]
> This is a valid GraphQL schema, just not fully supported by Sanity

@thompcd Does "this" refer to my schema here? ;-)

**Comment by camjc** [comment]
I reckon I’ve sorted it out, let me know if it works or still has issues :)

**Comment by bastibuck** [comment]
Will try and let you know, thx :-)

**Comment by bastibuck** [comment]
Works like a charm :-) Thx
