### ISSUE TITLE
Export to svg file

### ISSUE THREAD

**Issue by camjc** [ahmdigital/content-model-graph#7]
Its hard to share these right now, especially big ones. Give me a button!

**Comment by thompcd** [comment]
Is there a particular reason for exporting as svg rather than png?

**Comment by camjc** [comment]
Because it’s already an svg, and then it’ll be a vector instead of a certain resolution.

**Comment by thompcd** [comment]
Can create a utility function from handleSaveSVG function and add make the handler reference that if that's deemed necessary. The function should be portable

**Comment by camjc** [comment]
Closed by #21
